<a href="https://colab.research.google.com/github/Yaaxek/Pandas-transformaci-n-y-manipulaci-n-de-datos/blob/main/Desaf%C3%ADo_1_Ventas_Online.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

El objetivo de este proyecto es analizar los resultados de un evento con los clientes de una empresa de venta online. Se recopiló un conjunto de datos que contiene los clientes que más gastaron en productos durante los 5 días de ventas, que es la duración del evento. Este análisis identificará al cliente con la mayor compra esta semana, quien recibirá un premio de la tienda, y posteriormente, puede ayudar a la empresa a crear nuevas estrategias para atraer más clientes.

In [24]:
import pandas as pd

In [25]:
ventas=pd.read_json('/content/Ventas online.json')
ventas.head()

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [26]:
ventas=pd.json_normalize(ventas['dados_vendas'])
ventas.head()

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

Eliminar datos en listas dentro del DataFrame;

Verificar tipos de datos;

Identificar columnas numéricas;

Transformar la columna numérica a tipo numérico.

In [27]:
columnas=list(ventas.columns)
columnas

['Data de venda', 'Cliente', 'Valor da compra']

In [28]:
ventas=ventas.explode(columnas[1:])
ventas.head()

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31

In [29]:
ventas.reset_index(drop=True,inplace=True)
ventas.head()

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
1    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4    07/06/2022  Isabely JOanes 738       R$ 825,31

In [30]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [31]:
import numpy as np

In [32]:
ventas['Valor da compra']=ventas['Valor da compra'].apply(lambda x:x.replace('R$','').replace(',','.').strip())
ventas.head()

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321           836.5
1    06/06/2022  DieGO ARMANDIU 210          573.33
2    06/06/2022  DieGO ARMANDIU 210           392.8
3    06/06/2022  DieGO ARMANDIU 210          512.34
4    07/06/2022  Isabely JOanes 738          825.31

In [34]:
ventas['Valor da compra']=ventas['Valor da compra'].astype(np.float64)
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

In [35]:
ventas.head()

  Data de venda             Cliente  Valor da compra
0    06/06/2022     @ANA _LUCIA 321           836.50
1    06/06/2022  DieGO ARMANDIU 210           573.33
2    06/06/2022  DieGO ARMANDIU 210           392.80
3    06/06/2022  DieGO ARMANDIU 210           512.34
4    07/06/2022  Isabely JOanes 738           825.31

Debido a una inestabilidad en el sitio web de la empresa, tuvimos problemas con los nombres de los clientes durante el guardado. Esto resultó en una columna de nombres de clientes con una combinación de letras, mayúsculas y minúsculas, números y otros caracteres.

Sabiendo esto, manipula los textos de la columna Cliente para que el resultado sean los nombres de los clientes en letras minúsculas, con ausencia de caracteres especiales o números.

In [46]:
ventas['Cliente']=ventas['Cliente'].str.lower()
ventas['Cliente']=ventas['Cliente'].str.replace('[^a-z ]', '', regex=True).str.strip()
ventas.head()

  Data de venda         Cliente  Valor da compra
0    06/06/2022       ana lucia           836.50
1    06/06/2022  diego armandiu           573.33
2    06/06/2022  diego armandiu           392.80
3    06/06/2022  diego armandiu           512.34
4    07/06/2022  isabely joanes           825.31

El objetivo de este proyecto es analizar los resultados de un evento con los clientes de una empresa de venta online. Se recopiló un conjunto de datos que contiene los clientes que gastaron más en productos dentro de los 5 días posteriores a la venta, que es la duración del evento. Este análisis identificará al cliente con la mayor compra esa semana, quien recibirá un premio de la tienda, y posteriormente, puede ayudar a la empresa a crear nuevas estrategias para atraer más clientes.

In [50]:
ventas['Data de venda'] = pd.to_datetime(ventas['Data de venda'], format='%d/%m/%Y')

In [52]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes

In [53]:
compras=ventas.groupby(['Cliente'])['Valor da compra'].sum().sort_values(ascending=False)
compras.head()

Cliente
isabely joanes    2329.30
maria julia       2086.65
julya meireles    1643.74
diego armandiu    1478.47
paulo castro       899.16
Name: Valor da compra, dtype: float64